"""Auto-generated Hermes tool schemas from mundi.ai's tool surface.

DO NOT EDIT BY HAND. Regenerate via:
    python hermes_integration/codegen/generate_sage_tools.py

Sources:
  - src/geoprocessing/tools.json (60 GDAL/QGIS schemas)
  - sage_pydantic_schemas.json (29 Pydantic-derived schemas,
    of which 15 are unique to Pydantic and 14
    overlap with tools.json — overlap silently dropped, tools.json wins)

Schemas only. The actual handlers are built by `make_proxy_handler` in
`proxy.py`, which signs an HMAC request to mundi-app's /internal/tool-call
endpoint per dispatch.
"""
from __future__ import annotations

from typing import Any, Dict


GENERATED_SCHEMAS: Dict[str, Dict[str, Any]] = {
    'gdal_warpreproject': {
        'name': 'gdal_warpreproject',
        'description': 'Reprojects a raster layer to a different CRS.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Reprojects a raster layer to a different CRS'}, 'TARGET_CRS': {'type': 'string', 'description': 'Assigns a CRS to a raster input. Defaults to EPSG:4326 if not set.'}}, 'required': ['INPUT']},
    },
    'native_aggregate': {
        'name': 'native_aggregate',
        'description': 'Groups features in a vector layer by a chosen expression and calculates summary values for each group using specified aggregate functions.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Aggregates a vector or table layer using specified summary functions.'}, 'AGGREGATES': {'type': 'array', 'description': 'Aggregates vector layer fields using functions like sum or mean.', 'items': {'type': 'string'}}}, 'required': ['INPUT', 'AGGREGATES']},
    },
    'native_buffer': {
        'name': 'native_buffer',
        'description': 'Buffers vector layers to a specified distance in kilometers',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Input vector layer to buffer'}, 'DISTANCE': {'type': 'number', 'description': 'Buffer distance in kilometers. For example, 1 = 1 km, 5 = 5 km.', 'default': 1.0}}, 'required': ['INPUT']},
    },
    'native_dissolve': {
        'name': 'native_dissolve',
        'description': 'Merges features in a vector layer based on shared attributes or all features into one.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Dissolves features in a vector layer.'}}, 'required': ['INPUT']},
    },
    'native_fieldcalculator': {
        'name': 'native_fieldcalculator',
        'description': 'Adds or updates a field in a vector layer using a formula expression per feature',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Calculates a new or updated field in a vector layer using a formula'}, 'FIELD_NAME': {'type': 'string', 'description': 'Calculates a new or updated field in a vector layer using a formula.'}, 'FORMULA': {'type': 'string', 'description': 'Calculates a new or updated field for each vector feature using a QGIS expression formula.'}}, 'required': ['INPUT', 'FIELD_NAME', 'FORMULA']},
    },
    'native_fixgeometries': {
        'name': 'native_fixgeometries',
        'description': 'Repairs invalid geometries in a vector layer.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Repairs invalid geometries in a vector layer.'}}, 'required': ['INPUT']},
    },
    'native_geometrybyexpression': {
        'name': 'native_geometrybyexpression',
        'description': 'Modifies vector layer geometries using a geometry expression.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Modifies the geometry of vector layer features using an expression'}}, 'required': ['INPUT']},
    },
    'native_joinattributesbylocation': {
        'name': 'native_joinattributesbylocation',
        'description': 'Performs a spatial join by merging attributes from one vector layer to another where features meet a spatial relationship.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Joins attributes from one vector layer to another based on spatial relationship'}, 'JOIN': {'type': 'string', 'description': 'Joins attributes from a vector layer to another vector layer based on spatial location.'}}, 'required': ['INPUT', 'JOIN']},
    },
    'native_mergevectorlayers': {
        'name': 'native_mergevectorlayers',
        'description': 'Merges multiple vector layers of the same geometry type into one layer, keeping all fields and features.',
        'parameters': {'type': 'object', 'properties': {'LAYERS': {'type': 'array', 'description': 'Merges multiple vector layers of the same geometry type into one layer.', 'items': {'type': 'string'}}}, 'required': ['LAYERS']},
    },
    'native_reprojectlayer': {
        'name': 'native_reprojectlayer',
        'description': 'Reprojects a vector layer to another CRS.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Reprojects a vector layer to a different CRS'}, 'TARGET_CRS': {'type': 'string', 'description': 'Reprojects a vector layer to a different CRS.', 'default': 'EPSG:4326'}}, 'required': ['INPUT']},
    },
    'qgis_clip': {
        'name': 'qgis_clip',
        'description': 'Clips a vector layer using the boundaries of another vector polygon layer.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Clips features from a vector layer using the boundary of another vector layer.'}, 'OVERLAY': {'type': 'string', 'description': 'Clips a vector layer to polygons from another vector layer. Only features inside the overlay polygons are kept.'}}, 'required': ['INPUT', 'OVERLAY']},
    },
    'qgis_intersection': {
        'name': 'qgis_intersection',
        'description': 'Creates a new vector layer with features where the input and overlay layers intersect, combining attributes from both.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Intersects two vector layers and extracts overlapping features.'}, 'OVERLAY': {'type': 'string', 'description': 'Finds overlapping areas between two vector layers.'}}, 'required': ['INPUT', 'OVERLAY']},
    },
    'qgis_joinbylocationsummary': {
        'name': 'qgis_joinbylocationsummary',
        'description': 'Joins two vector layers by spatial relationship and adds summary statistics from the join layer to the input layer.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Joins vector layers by location and adds summary attributes from the join layer.'}, 'JOIN': {'type': 'string', 'description': 'Joins attributes from a vector layer based on spatial relationships with another vector layer.'}}, 'required': ['INPUT', 'JOIN']},
    },
    'qgis_statisticsbycategories': {
        'name': 'qgis_statisticsbycategories',
        'description': 'Calculates grouped statistics for vector layer attributes based on unique values in specified category fields. Outputs a summary table.',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Calculates statistics for a vector layer grouped by a category field.'}, 'CATEGORIES_FIELD_NAME': {'type': 'array', 'description': 'Calculates statistics for vector features grouped by values in the specified field(s)', 'items': {'type': 'string'}}}, 'required': ['INPUT', 'CATEGORIES_FIELD_NAME']},
    },
    'native_creategrid': {
        'name': 'native_creategrid',
        'description': 'Creates a regular grid of polygons (rectangles or hexagons) covering a specified extent. Useful for spatial sampling, heat maps, and aggregating point data into cells.',
        'parameters': {'type': 'object', 'properties': {'TYPE': {'type': 'integer', 'description': 'Grid type: 0=Point, 1=Line, 2=Rectangle, 3=Diamond, 4=Hexagon. Default: 2', 'default': 2}, 'EXTENT': {'type': 'string', 'description': "Grid extent as 'xmin,xmax,ymin,ymax [EPSG:code]'. Use a layer name to auto-detect extent."}, 'HSPACING': {'type': 'number', 'description': 'Horizontal spacing between grid cells (in CRS units, e.g. degrees for EPSG:4326)', 'default': 0.01}, 'VSPACING': {'type': 'number', 'description': 'Vertical spacing between grid cells (in CRS units)', 'default': 0.01}, 'CRS': {'type': 'string', 'description': 'CRS for the output grid. Default: EPSG:4326', 'default': 'EPSG:4326'}}, 'required': ['EXTENT']},
    },
    'native_zonalstatisticsfb': {
        'name': 'native_zonalstatisticsfb',
        'description': 'Calculates raster statistics (mean, min, max, sum, count, std dev) for each polygon zone in a vector layer. Creates a new layer with the statistics appended as columns. Use when the user wants to summarise raster values within polygons (e.g. average elevation per district, total rainfall per field).',
        'parameters': {'type': 'object', 'properties': {'INPUT': {'type': 'string', 'description': 'Vector polygon layer defining the zones'}, 'INPUT_RASTER': {'type': 'string', 'description': 'Raster layer to compute statistics from'}, 'RASTER_BAND': {'type': 'integer', 'description': 'Raster band number to analyse. Default: 1', 'default': 1}, 'COLUMN_PREFIX': {'type': 'string', 'description': "Prefix for the new statistic columns. Default: '_'", 'default': '_'}, 'STATISTICS': {'type': 'array', 'description': 'Statistics to compute: 0=Count, 1=Sum, 2=Mean, 3=Median, 4=StDev, 5=Min, 6=Max. Default: [2] (Mean)', 'items': {'type': 'integer'}, 'default': [2]}}, 'required': ['INPUT', 'INPUT_RASTER']},
    },
    'query_rwanda_zonal_stats': {
        'name': 'query_rwanda_zonal_stats',
        'description': "Query agricultural zonal statistics for Rwanda. Use query_type='district_summary' (DEFAULT) for per-district NDVI/crop overviews — works for all districts, a single province, or a single district. Use query_type='ndvi_timeseries' ONLY when you have a specific h3_index or parcel_id.",
        'parameters': {'type': 'object', 'properties': {'query_type': {'type': 'string', 'enum': ['district_summary', 'ndvi_timeseries'], 'description': 'district_summary: aggregated NDVI stats per district/province (no h3_index needed, this is the default). ndvi_timeseries: weekly NDVI time-series for a SPECIFIC h3_index or parcel_id (REQUIRED, will error without one).'}, 'district': {'type': 'string', 'description': 'District name to filter by (optional, for district_summary)'}, 'province': {'type': 'string', 'description': 'Province name to filter by (optional, for district_summary)'}, 'h3_index': {'type': 'string', 'description': 'H3 hexagon index — REQUIRED for ndvi_timeseries, not used for district_summary'}, 'parcel_id': {'type': 'string', 'description': 'Parcel ID — REQUIRED for ndvi_timeseries (alternative to h3_index), not used for district_summary'}, 'date_from': {'type': 'string', 'description': 'Start date in YYYY-MM-DD format (optional, for ndvi_timeseries)'}, 'date_to': {'type': 'string', 'description': 'End date in YYYY-MM-DD format (optional, for ndvi_timeseries)'}, 'week_start': {'type': 'string', 'description': 'Week start date in YYYY-MM-DD format (optional, for district_summary)'}}, 'required': ['query_type']},
    },
    'search_satellite_imagery': {
        'name': 'search_satellite_imagery',
        'description': 'Search for satellite imagery (Sentinel-2, Landsat) over Rwanda or a specific area. Returns available scenes with dates, cloud cover, and download links. Use this when the user asks about satellite images, remote sensing data, or wants to find imagery for a specific date/location.',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'west,south,east,north' in WGS84 coordinates. Defaults to Rwanda bounds if not specified."}, 'datetime_range': {'type': 'string', 'description': "Date range in ISO 8601 format like '2024-01-01/2024-06-30'. Defaults to last 30 days."}, 'max_cloud_cover': {'type': 'number', 'description': 'Maximum cloud cover percentage (0-100). Default: 20'}, 'limit': {'type': 'integer', 'description': 'Maximum number of results (1-50). Default: 10'}}, 'required': []},
    },
    'get_field_health': {
        'name': 'get_field_health',
        'description': 'Get real-time vegetation health statistics for a specific polygon/area using Sentinel Hub. Returns NDVI (and optionally NDWI, BSI) mean/std/min/max per day for the last 30 days. PREFERRED tool when the user asks about NDVI, crop health, vegetation, or field monitoring for a specific area, buffer zone, field, or any polygon that is NOT an admin boundary. Use the geometry from an existing layer on the map (buffer, drawn polygon, uploaded field boundary). WHEN TO USE: a user-drawn polygon, any geography, optionally a specific date. WHEN NOT TO USE: Rwanda admin boundary (district/sector/cell) — use get_agri_indices. Cached weekly aggregates — use get_ndvi_stats or get_parcel_ndvi_stats.',
        'parameters': {'type': 'object', 'properties': {'geometry': {'type': 'object', 'description': 'GeoJSON Polygon geometry of the field to analyse'}, 'date_from': {'type': 'string', 'description': 'Start date ISO 8601 (default: 30 days ago)'}, 'date_to': {'type': 'string', 'description': 'End date ISO 8601 (default: today)'}, 'index': {'type': 'string', 'enum': ['ndvi', 'multi'], 'description': "Index type: 'ndvi' for NDVI only, 'multi' for NDVI+NDWI+BSI. Default: ndvi"}}, 'required': ['geometry']},
    },
    'get_ndvi_stats': {
        'name': 'get_ndvi_stats',
        'description': "Read the latest NDVI vegetation index statistics for a single Rwanda district. Returns one weekly mean NDVI number. ONLY use for simple single-number NDVI lookups like 'what is the NDVI in Musanze'. Do NOT use for situation overviews, status reports, or assessment questions — use get_insurance_intelligence instead, which combines rainfall + NDVI + ET + dry spells + triggers into one report. WHEN TO USE: one weekly mean NDVI value for ONE named Rwanda district. WHEN NOT TO USE: sector/cell granularity — use get_cell_ndvi_stats. Real-time over a polygon — use get_field_health. User-uploaded field — use get_parcel_ndvi_stats.",
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'Filter results to a specific district name (e.g. Bugesera, Musanze, Gasabo)'}}, 'required': []},
    },
    'get_cell_ndvi_stats': {
        'name': 'get_cell_ndvi_stats',
        'description': 'Read NDVI vegetation index statistics at sector or cell level within a district. Returns sector_name and cell_name in every row so results can be grouped by sector. When sector is provided, returns only cells in that sector. When only district is provided, returns all sectors with their cells. Use as a SUPPLEMENT after get_insurance_intelligence when the user wants spatial breakdown. Do NOT use as the primary tool for situation/overview questions. WHEN TO USE: sector- or cell-level NDVI within a named Rwanda district. WHEN NOT TO USE: district-level summary — use get_ndvi_stats. User-uploaded polygon — use get_parcel_ndvi_stats.',
        'parameters': {'type': 'object', 'properties': {'cell_name': {'type': 'string', 'description': 'Filter by cell name (partial match supported)'}, 'sector': {'type': 'string', 'description': 'Filter by sector name to see all cells within a sector'}, 'district': {'type': 'string', 'description': 'Filter by district name to see all sectors and cells within a district'}}, 'required': []},
    },
    'get_soil_properties': {
        'name': 'get_soil_properties',
        'description': "Query African soil properties at a specific location using iSDAsoil's 30m resolution machine learning predictions. Returns soil pH, nitrogen, phosphorus, potassium, organic carbon, clay/sand/silt content, texture class, and 12+ other properties. Each property includes depth (0-20cm or 20-50cm) and uncertainty estimates. Use when the user asks about soil quality, fertility, nutrients, texture, or agronomic suitability at a specific location in Africa.",
        'parameters': {'type': 'object', 'properties': {'longitude': {'type': 'number', 'description': 'Longitude in decimal degrees (WGS84), e.g. 30.05'}, 'latitude': {'type': 'number', 'description': 'Latitude in decimal degrees (WGS84), e.g. -2.30'}, 'properties': {'type': 'array', 'items': {'type': 'string', 'enum': ['ph', 'nitrogen_total', 'phosphorous_extractable', 'potassium_extractable', 'carbon_organic', 'clay_content', 'sand_content', 'silt_content', 'bulk_density', 'cation_exchange_capacity', 'calcium_extractable', 'magnesium_extractable', 'iron_extractable', 'sulphur_extractable', 'zinc_extractable', 'aluminium_extractable', 'carbon_total', 'stone_content', 'bedrock_depth', 'texture_class', 'fcc']}, 'description': 'List of soil properties to query. Defaults to 8 most useful for agriculture: ph, nitrogen_total, phosphorous_extractable, potassium_extractable, carbon_organic, clay_content, sand_content, texture_class'}, 'depth': {'type': 'string', 'enum': ['0-20', '20-50'], 'description': 'Soil depth range in centimeters. Default: 0-20'}}, 'required': ['longitude', 'latitude']},
    },
    'get_parcel_ndvi_stats': {
        'name': 'get_parcel_ndvi_stats',
        'description': 'Read parcel-level NDVI statistics from the DuckDB cache for user-uploaded field boundaries. Updated nightly by Dagster at 10m native Sentinel-2 resolution. These are individual farm fields uploaded by users and tagged with rwanda_parcels=true. Returns per-parcel mean, std, min, max NDVI and estimated area. Use when the user asks about specific fields, farm parcels, or individual plot vegetation health. WHEN TO USE: user-uploaded field boundary by slug or name (e.g. Cyampirita, Kabarama, Kabari). WHEN NOT TO USE: Rwanda admin boundary — use get_ndvi_stats or get_cell_ndvi_stats. Real-time on an arbitrary polygon — use get_field_health.',
        'parameters': {'type': 'object', 'properties': {'parcel_name': {'type': 'string', 'description': 'Filter by parcel/field name (partial match supported)'}, 'layer_id': {'type': 'string', 'description': 'Filter by source layer ID'}}, 'required': []},
    },
    'get_agri_indices': {
        'name': 'get_agri_indices',
        'description': 'Get REAL-TIME agricultural vegetation indices for Rwanda ADMINISTRATIVE BOUNDARIES only (districts, sectors, cells). Computes 6 indices: NDVI, EVI, NDWI, SAVI, NDRE, NDBI. Only use when the user explicitly asks for district/sector/cell level analysis. Do NOT use for custom areas, buffers, fields, or drawn polygons — use get_field_health instead for those. WHEN TO USE: Rwanda ADMIN boundaries (district/sector/cell) needing live multi-index values now. WHEN NOT TO USE: user-drawn polygon — use get_field_health. Pre-aggregated weekly NDVI only — use get_ndvi_stats or get_cell_ndvi_stats.',
        'parameters': {'type': 'object', 'properties': {'admin_level': {'type': 'string', 'enum': ['district', 'sector', 'cell'], 'description': "Administrative level: 'district' (30 units), 'sector' (416 units, ADM3), 'cell' (2148 units, ADM4). Default: district"}, 'name': {'type': 'string', 'description': "Filter to a specific admin unit name (e.g. 'Gasabo', 'Kimisagara'). Partial match supported."}, 'district': {'type': 'string', 'description': 'Filter sectors/cells within a specific district'}, 'date_from': {'type': 'string', 'description': 'Start date ISO 8601 (default: 7 days ago)'}, 'date_to': {'type': 'string', 'description': 'End date ISO 8601 (default: today)'}}, 'required': []},
    },
    'add_land_cover_layer': {
        'name': 'add_land_cover_layer',
        'description': "Add ESRI 10m Annual LULC 2024 land cover layer to the map. Shows cropland vs non-cropland at 10m resolution from satellite imagery. Two modes: 'all' shows all 9 land cover classes (water, trees, flooded vegetation, crops, built area, bare ground, snow/ice, clouds, rangeland). 'cropland' highlights cropland in green and mutes everything else. IMPORTANT: always clip to the area of interest. Preferred: pass bbox from the relevant layer's bounds in MapState. Alternative: pass lat+lon to auto-detect the correct admin boundary. NEVER guess district names. NEVER show the entire country unless the user explicitly asks for it. WHEN TO USE: the user wants to SEE land cover on the map. WHEN NOT TO USE: numeric land-cover area or percentage for a region — use query_worldcover_stats. This tool only adds a visual layer.",
        'parameters': {'type': 'object', 'properties': {'mode': {'type': 'string', 'enum': ['all', 'cropland'], 'description': "Visualization mode: 'all' shows all 9 land cover classes with distinct colours. 'cropland' highlights cropland areas in green and mutes all other classes. Default: all"}, 'lat': {'type': 'number', 'description': 'Latitude (EPSG:4326) of the point of interest. The tool auto-detects the containing district/sector/cell from PostGIS for clipping. Use this instead of guessing district names.'}, 'lon': {'type': 'number', 'description': 'Longitude (EPSG:4326) of the point of interest.'}, 'bbox': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 4, 'maxItems': 4, 'description': 'Bounding box [west, south, east, north] in EPSG:4326 to clip the layer to. Use when the user refers to a custom area (buffer circle, drawn polygon, existing layer extent). Extract the bounds from the relevant layer in MapState.'}, 'district': {'type': 'string', 'description': 'Rwanda district name — only use if the user explicitly names a district. Prefer lat/lon or bbox instead.'}, 'sector': {'type': 'string', 'description': 'Rwanda sector name — only use if the user explicitly names a sector.'}, 'cell': {'type': 'string', 'description': 'Rwanda cell name — only use if the user explicitly names a cell.'}}, 'required': []},
    },
    'query_worldcover_stats': {
        'name': 'query_worldcover_stats',
        'description': "Query ESRI 10m LULC 2024 land-cover statistics for a specific area. Two query types: 'land_cover' returns area in hectares for each land-cover class (crops, trees, rangeland, etc.). 'largest_cropland' returns the biggest contiguous cropland plantations ranked by area. IMPORTANT: always scope to the user's area of interest. Preferred: pass bbox from the relevant layer's bounds in MapState. Alternative: pass lat+lon from the Center Point layer — the tool will auto-detect the correct admin boundary. NEVER guess district names — use bbox or lat/lon and let the tool resolve the location.",
        'parameters': {'type': 'object', 'properties': {'query_type': {'type': 'string', 'enum': ['land_cover', 'largest_cropland'], 'description': 'land_cover: area breakdown by land-cover class (DEFAULT). largest_cropland: ranked list of biggest contiguous cropland areas.'}, 'lat': {'type': 'number', 'description': 'Latitude (EPSG:4326) of the point of interest. The tool auto-detects the containing district/sector/cell from PostGIS. Use this instead of guessing district names.'}, 'lon': {'type': 'number', 'description': 'Longitude (EPSG:4326) of the point of interest.'}, 'bbox': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 4, 'maxItems': 4, 'description': 'Bounding box [west, south, east, north] in EPSG:4326. Use when the user refers to a custom area (buffer circle, drawn polygon, existing layer extent). Extract the bounds from the relevant layer in MapState. This performs on-the-fly analysis for the exact area.'}, 'district': {'type': 'string', 'description': 'Rwanda district name — only use if the user explicitly names a district. Prefer lat/lon or bbox instead.'}, 'sector': {'type': 'string', 'description': 'Rwanda sector name — only use if the user explicitly names a sector.'}, 'cell': {'type': 'string', 'description': 'Rwanda cell name — only use if the user explicitly names a cell.'}, 'limit': {'type': 'integer', 'description': 'Max results for largest_cropland query. Default: 10'}}, 'required': []},
    },
    'get_crop_classifications': {
        'name': 'get_crop_classifications',
        'description': "Read the latest pre-computed crop classification results from the DuckDB cache. These are generated weekly by Dagster. Returns classification labels, areas, and confidence for each district. Use ONLY when the user asks specifically about crop classification maps or land use mapping. Do NOT use when the user asks 'what about other crops' after a situation report — use get_insurance_intelligence with a different crop parameter instead. Pass lat+lon to auto-detect the correct district — NEVER guess district names. WHEN TO USE: read the most recent weekly crop classification result for parcels from the cache. WHEN NOT TO USE: classify a parcel that has not been processed yet — use identify_parcel_crop.",
        'parameters': {'type': 'object', 'properties': {'lat': {'type': 'number', 'description': 'Latitude (EPSG:4326) of the point of interest. Auto-detects the containing district from PostGIS.'}, 'lon': {'type': 'number', 'description': 'Longitude (EPSG:4326) of the point of interest.'}, 'district': {'type': 'string', 'description': 'District name — only use if the user explicitly names a district. Prefer lat/lon instead.'}}, 'required': []},
    },
    'get_anomaly_alerts': {
        'name': 'get_anomaly_alerts',
        'description': 'Read the latest vegetation anomaly alerts. Returns locations where NDVI dropped significantly below normal, indicating crop stress, drought, or disease. Use alongside get_insurance_intelligence for situation overviews — it adds spatial hotspot detail. Also use standalone when the user asks specifically about crop problems, stress alerts, or anomalies.',
        'parameters': {'type': 'object', 'properties': {'severity': {'type': 'string', 'enum': ['high', 'moderate'], 'description': 'Filter by severity level'}, 'district': {'type': 'string', 'description': 'Filter to a specific district'}}, 'required': []},
    },
    'get_yield_risk': {
        'name': 'get_yield_risk',
        'description': 'Read pre-computed yield risk assessments from the DuckDB cache. Uses Mann-Kendall trend analysis and Theil-Sen slope on NDVI time series to predict crop yield risk per district. Returns risk level (low/normal/moderate/high/critical), trend direction, and statistical confidence. Use when the user asks about harvest outlook, yield forecast, or crop risk.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'Filter to a specific district'}}, 'required': []},
    },
    'get_drought_status': {
        'name': 'get_drought_status',
        'description': 'Read pre-computed drought status from the DuckDB cache. Uses Vegetation Condition Index (VCI) with NDWI water stress analysis per district. Returns drought status (normal/watch/moderate_drought/severe_drought), VCI score, and affected period count. Use when the user asks about drought, water stress, or dry conditions. WHEN TO USE: drought severity now (VCI + NDWI). WHEN NOT TO USE: forward-looking yield risk — use get_yield_risk. Recent NDVI drop alerts — use get_anomaly_alerts. Historical no-rain windows — use detect_dry_spells.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'Filter to a specific district'}, 'status': {'type': 'string', 'enum': ['severe_drought', 'moderate_drought', 'watch', 'normal'], 'description': 'Filter by drought status'}}, 'required': []},
    },
    'get_crop_growth_stage': {
        'name': 'get_crop_growth_stage',
        'description': 'Read pre-computed crop growth stage analysis from the DuckDB cache. Uses NDVI phenology curve analysis to identify current crop stage per district: dormant, green_up, peak, senescence, or harvest. Returns current stage, peak NDVI date, and key phenological transition dates. Use when the user asks about crop growth, planting, harvesting, or growing season.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'Filter to a specific district'}, 'stage': {'type': 'string', 'enum': ['dormant', 'green_up', 'peak', 'senescence', 'harvest', 'stable'], 'description': 'Filter by current growth stage'}}, 'required': []},
    },
    'get_weather_stats': {
        'name': 'get_weather_stats',
        'description': 'Read daily weather statistics from the PostgreSQL cache. Data comes from Copernicus AgERA5 agrometeorological indicators at 0.1° (~10km) grid resolution, aggregated to district level. Returns daily temperature (mean/max/min °C), precipitation (mm/day), and solar radiation (MJ/m²/day). NOTE: Results are district-level averages. Actual conditions vary within a district due to elevation, terrain, and microclimates. For location-specific weather, use get_forecast with exact lat/lon instead. Use this tool for HISTORICAL weather only.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'Filter to a specific district name (e.g. Bugesera, Musanze, Gasabo)'}, 'date_from': {'type': 'string', 'description': 'Start date in YYYY-MM-DD format (default: 30 days ago)'}, 'date_to': {'type': 'string', 'description': 'End date in YYYY-MM-DD format (default: today)'}}, 'required': []},
    },
    'get_forecast': {
        'name': 'get_forecast',
        'description': 'Get weather forecast for any location in Rwanda. Fuses 4 models — ECMWF IFS (9km), GFS (13km), ICON (11km), GraphCast AI (28km) — for consensus forecasts with risk assessment. Returns daily temperature, precipitation, wind, ET0, soil moisture, and a natural-language risk briefing. Each location gets unique interpolated values (sector-level precision). Use when the user asks about weather forecast, future weather, expected rainfall, upcoming conditions, or any forward-looking weather question.',
        'parameters': {'type': 'object', 'properties': {'latitude': {'type': 'number', 'description': 'Latitude of the location (e.g. -1.9403 for Kigali)'}, 'longitude': {'type': 'number', 'description': 'Longitude of the location (e.g. 29.8739 for Kigali)'}, 'district': {'type': 'string', 'description': 'Rwanda district name — will use district centroid if lat/lon not provided'}, 'forecast_days': {'type': 'integer', 'description': 'Number of days to forecast (1-16, default 10)'}}, 'required': []},
    },
    'get_forecast_accuracy': {
        'name': 'get_forecast_accuracy',
        'description': 'Compare weather forecast against observed AgERA5 weather data to measure accuracy. Returns MAE (Mean Absolute Error) and bias for temperature and precipitation across districts where both forecast and observation exist. Use when the user asks about forecast accuracy, model performance, how good the forecast is, or weather prediction quality.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'Specific district to check accuracy for (optional — defaults to all districts)'}, 'lookback_days': {'type': 'integer', 'description': 'Number of days to look back for accuracy comparison. Default: 30'}}, 'required': []},
    },
    'get_emissions_stats': {
        'name': 'get_emissions_stats',
        'description': 'Read annual greenhouse gas and air pollutant emissions from the PostgreSQL cache. Data comes from EDGAR v8.0 (JRC, 0.1 degree resolution, updated annually by Dagster). Returns per-district annual emissions in tonnes for agriculture-related gases. Sectors: AGS (agricultural soils / fertilizers), ENF (enteric fermentation / livestock), MNM (manure management), AWB (agricultural waste burning). Use when the user asks about emissions, greenhouse gases, methane, CH4, N2O, CO2, NH3, fertilizer emissions, livestock emissions, or agricultural pollution for Rwanda districts.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'Filter to a specific district name (e.g. Musanze, Gasabo, Bugesera)'}, 'year': {'type': 'integer', 'description': 'Filter to a specific year (e.g. 2022)'}, 'year_from': {'type': 'integer', 'description': 'Start year for range filter (default: 5 years ago)'}, 'year_to': {'type': 'integer', 'description': 'End year for range filter (default: latest available)'}, 'emission_type': {'type': 'string', 'enum': ['CH4', 'N2O', 'CO2', 'NH3'], 'description': 'Filter by gas: CH4 (methane), N2O (nitrous oxide), CO2 (carbon dioxide), NH3 (ammonia)'}, 'sector': {'type': 'string', 'enum': ['AGS', 'ENF', 'MNM', 'AWB'], 'description': 'Filter by agriculture sector: AGS (agricultural soils), ENF (enteric fermentation), MNM (manure management), AWB (agricultural waste burning)'}}, 'required': []},
    },
    'create_management_zones': {
        'name': 'create_management_zones',
        'description': 'Create NDVI-based management zones for a field or farm polygon. Divides the area into productivity zones (Low/Medium/High) using satellite vegetation data and K-means clustering. Returns zone polygons as a map layer with NDVI statistics per zone. Use when the user asks about management zones, productivity mapping, variable-rate zones, or field zoning.',
        'parameters': {'type': 'object', 'properties': {'geometry': {'type': 'object', 'description': 'GeoJSON Polygon geometry of the field boundary'}, 'num_zones': {'type': 'integer', 'description': 'Number of zones to create (2-5, default 3)'}, 'date_from': {'type': 'string', 'description': 'Start date ISO 8601 (default: 30 days ago)'}, 'date_to': {'type': 'string', 'description': 'End date ISO 8601 (default: today)'}}, 'required': ['geometry']},
    },
    'create_prescription_map': {
        'name': 'create_prescription_map',
        'description': 'Create a variable-rate fertilizer prescription map for a field. Combines NDVI management zones with iSDAsoil data and Rwanda Agriculture Board crop-specific baseline rates. Returns zone polygons with N/P/K recommendations in kg/ha. Use when the user asks about fertilizer recommendations, prescription maps, or variable-rate application.',
        'parameters': {'type': 'object', 'properties': {'geometry': {'type': 'object', 'description': 'GeoJSON Polygon geometry of the field boundary'}, 'crop_type': {'type': 'string', 'enum': ['maize', 'beans', 'rice', 'wheat', 'sorghum', 'potato', 'cassava'], 'description': 'Crop type for baseline fertilizer rates (default: maize)'}, 'num_zones': {'type': 'integer', 'description': 'Number of management zones (2-5, default 3)'}}, 'required': ['geometry']},
    },
    'create_soil_sampling_plan': {
        'name': 'create_soil_sampling_plan',
        'description': 'Create an optimized soil sampling plan for a field. Places 1-2 sampling points per NDVI management zone at representative locations. Returns point locations with sampling instructions and priority. Use when the user asks about soil testing, soil sampling, or where to collect soil samples.',
        'parameters': {'type': 'object', 'properties': {'geometry': {'type': 'object', 'description': 'GeoJSON Polygon geometry of the field boundary'}, 'num_zones': {'type': 'integer', 'description': 'Number of management zones for stratification (2-5, default 3)'}}, 'required': ['geometry']},
    },
    'identify_parcel_crop': {
        'name': 'identify_parcel_crop',
        'description': "Identify what crop is growing on a field parcel using Sentinel-2 NDVI time-series and temporal signature matching. Compares the observed growth curve against known Rwanda crop profiles (maize, beans, cassava, rice, sorghum, banana, tea, coffee, potato, wheat, fallow). Returns the most likely crop with confidence score and ranked alternatives. PREFERRED tool when farmer asks 'what crop is on my field?', 'can you detect what I planted?', or 'identify the crop'. Requires a polygon geometry (field boundary). WHEN TO USE: classify ONE specific parcel right now from Sentinel-2 time-series. WHEN NOT TO USE: look up an already-classified parcel — call get_crop_classifications first (cached weekly). General 'what crops grow here' — use get_entity or search_brain.",
        'parameters': {'type': 'object', 'properties': {'geometry': {'type': 'object', 'description': 'GeoJSON Polygon geometry of the field/parcel boundary'}, 'months': {'type': 'integer', 'description': 'Number of months of NDVI history to analyze (default: 6, min: 3)'}}, 'required': ['geometry']},
    },
    'confirm_crop_prediction': {
        'name': 'confirm_crop_prediction',
        'description': "Record farmer confirmation or correction of a crop prediction. When Ingabe predicts a crop type for a parcel and the farmer says 'yes that's correct' or 'no, it's actually beans', use this tool to store the feedback as ground truth. This data improves future predictions. Use when the user confirms or corrects a crop identification result.",
        'parameters': {'type': 'object', 'properties': {'geometry': {'type': 'object', 'description': 'GeoJSON Polygon geometry of the field/parcel'}, 'predicted_crop': {'type': 'string', 'description': 'The crop that Ingabe predicted (from identify_parcel_crop result)'}, 'actual_crop': {'type': 'string', 'description': 'The actual crop the farmer confirms or corrects to'}, 'confirmed': {'type': 'boolean', 'description': 'true if farmer confirms prediction was correct, false if corrected'}, 'season': {'type': 'string', 'description': "Growing season (e.g. '2026A', '2026B'). Auto-detected if omitted."}}, 'required': ['predicted_crop', 'actual_crop', 'confirmed']},
    },
    'get_soil_moisture': {
        'name': 'get_soil_moisture',
        'description': 'Query relative soil moisture from FAO WaPOR v3 at 100m dekadal (10-day) resolution. Returns a time series of soil moisture percentage for the given location. Use when the user asks about soil moisture, soil wetness, soil dryness, irrigation needs, or water availability in the soil. WHEN TO USE: WaPOR 100m dekadal (10-day) area-aggregated soil moisture, optical-derived. WHEN NOT TO USE: point measurement at sub-daily cadence that sees through clouds and vegetation — use get_cygnss_soil_moisture. Soil texture/chemistry — use get_soil_properties.',
        'parameters': {'type': 'object', 'properties': {'latitude': {'type': 'number', 'description': 'Latitude in decimal degrees (WGS84)'}, 'longitude': {'type': 'number', 'description': 'Longitude in decimal degrees (WGS84)'}, 'date_from': {'type': 'string', 'description': 'Start date (YYYY-MM-DD). Default: 30 days ago'}, 'date_to': {'type': 'string', 'description': 'End date (YYYY-MM-DD). Default: latest available'}}, 'required': ['latitude', 'longitude']},
    },
    'get_evapotranspiration': {
        'name': 'get_evapotranspiration',
        'description': 'Query actual evapotranspiration (ET) and optionally transpiration and net primary productivity from FAO WaPOR v3 at 100m dekadal (10-day) resolution. Returns a time series of ET values in mm/day for the given location. Use when the user asks about evapotranspiration, water use, crop water consumption, water productivity, ET, or how much water a crop/field is using.',
        'parameters': {'type': 'object', 'properties': {'latitude': {'type': 'number', 'description': 'Latitude in decimal degrees (WGS84)'}, 'longitude': {'type': 'number', 'description': 'Longitude in decimal degrees (WGS84)'}, 'date_from': {'type': 'string', 'description': 'Start date (YYYY-MM-DD). Default: 30 days ago'}, 'date_to': {'type': 'string', 'description': 'End date (YYYY-MM-DD). Default: latest available'}, 'include_components': {'type': 'boolean', 'description': 'If true, also return transpiration and net primary productivity. Default: false'}}, 'required': ['latitude', 'longitude']},
    },
    'get_food_security_alerts': {
        'name': 'get_food_security_alerts',
        'description': 'Query IPC food security classifications for Rwanda from FEWS NET. Returns the current IPC phase (1-5 scale: 1=Minimal, 2=Stressed, 3=Crisis, 4=Emergency, 5=Famine) and any areas of concern. Use when the user asks about food security, hunger, famine risk, IPC classification, food crisis, or food insecurity in Rwanda.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'Optional district name to filter (e.g. Kayonza, Bugesera)'}, 'period': {'type': 'string', 'enum': ['current', 'projected'], 'description': 'current = latest observed situation, projected = near-term outlook. Default: current'}}, 'required': []},
    },
    'detect_dry_spells': {
        'name': 'detect_dry_spells',
        'description': 'Detect historical dry spells from observed weather data (AgERA5). Scans for consecutive days where precipitation was below a threshold. Use when the user asks about dry spells, drought events, consecutive dry days, rainfall gaps, or historical drought periods for Rwanda districts.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'District name to filter (e.g. Gasabo, Bugesera). Optional — defaults to all districts'}, 'date_from': {'type': 'string', 'description': 'Start date (YYYY-MM-DD). Default: 180 days ago'}, 'date_to': {'type': 'string', 'description': 'End date (YYYY-MM-DD). Default: latest available'}, 'threshold_mm': {'type': 'number', 'description': 'Daily precipitation threshold in mm — days below this count as dry. Default: 2.0'}, 'min_duration_days': {'type': 'integer', 'description': 'Minimum consecutive dry days to qualify as a dry spell. Default: 10'}}, 'required': []},
    },
    'get_insurance_accuracy': {
        'name': 'get_insurance_accuracy',
        'description': 'Compute weather data accuracy for agricultural insurance underwriting. Returns binary rainfall detection metrics (POD, FAR, HSS, CSI), dry spell detection results, NDVI-weather concordance, and an overall confidence rating (0-100). Use when the user asks about insurance accuracy, weather data reliability, rainfall detection quality, underwriting confidence, or whether weather data is good enough for crop insurance.',
        'parameters': {'type': 'object', 'properties': {'district': {'type': 'string', 'description': 'District name (e.g. Gasabo, Bugesera). Optional — defaults to all districts'}, 'season': {'type': 'string', 'enum': ['A', 'B'], 'description': 'Rwanda growing season: A (Sep-Jan) or B (Feb-Jun). Optional — defaults to last 90 days'}, 'threshold_mm': {'type': 'number', 'description': 'Rainfall threshold in mm for binary rain/no-rain classification. Default: 5.0'}}, 'required': []},
    },
    'get_insurance_intelligence': {
        'name': 'get_insurance_intelligence',
        'description': "Get a comprehensive agricultural situation report for any location in Rwanda. This is the PRIMARY tool for any question about the 'situation', 'status', 'overview', 'how is [place] doing', or 'what's happening in [place]'. Combines rainfall (CHIRPS cumulative + SPI drought index), vegetation health (NDVI + Sentinel-1 SAR), evapotranspiration (WaPOR), soil moisture, dry spells, season progress, parametric trigger thresholds, and multi-model forecast outlook (ECMWF IFS + GFS + ICON + GraphCast) into one unified report. Reports are location-based (not crop-specific) — they show weather and vegetation conditions for the area regardless of what is planted. Supports 4 audience views: farmer (simple), insurance (trigger table), agronomist (technical + recommendations), scientist (full methodology). Works at any admin level: district, sector, cell, or village. COMPARISON MODE: when the user asks to compare areas (e.g. 'compare sectors in Nyamasheke', 'which districts get more rain', 'difference between sectors'), set compare_level to the level being compared. This returns ALL signals for every child area in one call. IMPORTANT: at least one location parameter (district, sector, cell, or village) is required. WHEN TO USE: open-ended 'what is happening here' / 'how is this farm doing' over a Rwanda location — fuses NDVI + weather + drought + crop into one report. WHEN NOT TO USE: the user asked one narrow question (just rainfall, just NDVI, just soil) — call the specific tool. Do NOT default to this for every Rwanda question.",
        'parameters': {'type': 'object', 'properties': {'crop': {'type': 'string', 'description': 'Optional crop name if the user explicitly mentions one. The report shows location-based conditions (rainfall, NDVI, soil moisture, etc) regardless — we cannot detect what crop is planted from satellite. Leave empty or omit for general location reports.'}, 'season': {'type': 'string', 'enum': ['A', 'B'], 'description': 'Growing season: A (Sep-Feb) or B (Feb-Jul). Auto-detected if omitted'}, 'district': {'type': 'string', 'description': 'District name (e.g. Musanze, Gasabo, Bugesera)'}, 'sector': {'type': 'string', 'description': 'Sector name within a district (e.g. Kinigi, Kimironko)'}, 'cell': {'type': 'string', 'description': 'Cell name within a sector'}, 'village': {'type': 'string', 'description': 'Village name — most specific admin level'}, 'audience': {'type': 'string', 'enum': ['farmer', 'insurance', 'agronomist', 'scientist'], 'description': 'Who is reading this report. Default: farmer'}, 'compare_level': {'type': 'string', 'enum': ['district', 'sector', 'cell'], 'description': "COMPARISON MODE: set this to compare all child areas at this admin level. 'sector' with district=X compares all sectors in district X. 'cell' with sector=Y compares all cells in sector Y. 'district' compares all 30 districts nationwide. Returns rainfall, SPI, NDVI, soil moisture, ET, temperature, SAR, and dry spells for every area. Only set this when the user asks to COMPARE areas — omit for single-location reports."}}, 'required': []},
    },
    'predict_ndvi_from_sar': {
        'name': 'predict_ndvi_from_sar',
        'description': 'Predict NDVI vegetation index from Sentinel-1 SAR radar data when optical imagery is blocked by clouds. Uses 30-day SAR backscatter trajectory to estimate what NDVI would be. Use when the user asks about crop health during cloudy periods or wants cloud-proof monitoring.',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'lon_min,lat_min,lon_max,lat_max'"}, 'target_date': {'type': 'string', 'description': 'Date to predict NDVI for (YYYY-MM-DD). Default: today'}}, 'required': ['bbox']},
    },
    'detect_water_bodies': {
        'name': 'detect_water_bodies',
        'description': 'Detect water bodies and ponds from Sentinel-1 SAR radar imagery. Works through clouds and under tree canopy. Use for aquaculture pond verification, water body monitoring, or checking if ponds are filled. Returns water area in hectares and water body polygons.',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'lon_min,lat_min,lon_max,lat_max'"}, 'date': {'type': 'string', 'description': 'Target date (YYYY-MM-DD). Default: most recent S1 pass'}}, 'required': ['bbox']},
    },
    'detect_flood_extent': {
        'name': 'detect_flood_extent',
        'description': 'Delineate flood extent by comparing Sentinel-1 SAR radar imagery from before and after a flood event. Returns new flood area (excluding permanent water bodies) with polygons suitable for insurance claim validation.',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'lon_min,lat_min,lon_max,lat_max'"}, 'date_before': {'type': 'string', 'description': 'Pre-flood date (YYYY-MM-DD)'}, 'date_after': {'type': 'string', 'description': 'Post-flood date (YYYY-MM-DD)'}}, 'required': ['bbox', 'date_before', 'date_after']},
    },
    'get_alos_l_band_stats': {
        'name': 'get_alos_l_band_stats',
        'description': 'Get ALOS-2 PALSAR-2 L-band (24cm wavelength) SAR backscatter statistics for a bounding box over one or more years. Returns per-year HH/HV gamma-naught stats plus the HH/HV ratio in dB. The HH/HV ratio discriminates vegetation structure: forest <-5dB, crops -5 to -10dB, bare/water >-3dB. L-band penetrates dense canopy where Sentinel-1 C-band saturates. Use for crop-type discrimination, biomass analysis, or deep canopy monitoring. No auth needed (Digital Earth Africa public bucket).',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'lon_min,lat_min,lon_max,lat_max'"}, 'years': {'type': 'string', 'description': "Comma-separated years to analyse (e.g. '2020,2021,2022'). Available: 2015-2022 (PALSAR-2), 2007-2010 (PALSAR). Default: 2020,2021,2022"}}, 'required': ['bbox']},
    },
    'get_alos_temporal_variation': {
        'name': 'get_alos_temporal_variation',
        'description': 'Compute year-over-year variation in ALOS PALSAR L-band HH/HV ratio across multiple years. Reveals agricultural activity patterns: stable ratio = perennial crops/forest, variable ratio = annual crop rotation, high HV std = heterogeneous smallholder mosaics. Use for long-term land-use change analysis or distinguishing perennial vs annual cropping systems.',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'lon_min,lat_min,lon_max,lat_max'"}, 'years': {'type': 'string', 'description': 'Comma-separated years (need at least 2). Default: 2018,2019,2020,2021,2022'}}, 'required': ['bbox']},
    },
    'check_cygnss_availability': {
        'name': 'check_cygnss_availability',
        'description': "Check what NASA CYGNSS (GNSS-Reflectometry) data is available for a bounding box. CYGNSS is an 8-satellite constellation that measures GPS signal reflections to detect soil moisture and surface water. Coverage ±38° latitude (Rwanda is dead center), median 3-hour revisit, ~6-day latency. CYGNSS's killer feature: L-band penetrates vegetation canopy, detecting water UNDER trees where Sentinel-1 and optical fail. Returns granule counts, latest dates, and auth status. No auth needed for this diagnostic tool. Use first before calling get_cygnss_soil_moisture or get_cygnss_watermask.",
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'lon_min,lat_min,lon_max,lat_max'. Default: Rwanda national bbox."}}, 'required': []},
    },
    'get_cygnss_soil_moisture': {
        'name': 'get_cygnss_soil_moisture',
        'description': 'Get CYGNSS soil moisture timeseries for a point (lat/lon). Returns volumetric water content (m³/m³, 0-5cm depth) at 9km or 36km resolution. Interpretation: <0.10 dry, 0.10-0.25 moist, 0.25-0.40 wet/flood risk, >0.40 likely standing water. Complements WaPOR (100m dekadal) with higher temporal resolution. Requires NASA Earthdata credentials — if unavailable, returns granule availability without data. Use for drought monitoring, irrigation planning, or flood risk at a specific field.',
        'parameters': {'type': 'object', 'properties': {'lat': {'type': 'number', 'description': 'Latitude in decimal degrees (Rwanda: -2.84 to -1.05)'}, 'lon': {'type': 'number', 'description': 'Longitude in decimal degrees (Rwanda: 28.86 to 30.90)'}, 'days_back': {'type': 'integer', 'description': 'How many days of history to pull. Default: 90'}, 'resolution_km': {'type': 'integer', 'description': 'Grid resolution, 9 or 36 km. Default: 9'}}, 'required': ['lat', 'lon']},
    },
    'get_cygnss_watermask': {
        'name': 'get_cygnss_watermask',
        'description': 'Get CYGNSS binary water/land classification at ~1km resolution for a bounding box. L-band GNSS-R detects water under vegetation canopy — ponds hidden under banana groves show up here where Sentinel-1 fails. Coarser than SAR water detection (detect_water_bodies at ~10m) but sees through canopy. Use for aquaculture pond verification under forest cover, or cross-validating Sentinel-1 flood extent. Requires NASA Earthdata credentials.',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'lon_min,lat_min,lon_max,lat_max'"}, 'date': {'type': 'string', 'description': 'Target date (YYYY-MM-DD). Default: 7 days ago (accounting for 6-day latency)'}, 'product': {'type': 'string', 'description': "'watermask_daily' (1km, daily) or 'watermask_monthly' (1km, monthly). Default: watermask_daily"}}, 'required': ['bbox']},
    },
    'search_brain': {
        'name': 'search_brain',
        'description': 'Search the knowledge brain for entities and information. Uses hybrid search (keyword + vector) across brain pages. Returns ranked results with compiled truth summaries. Use when the user asks about a field, farmer, district, claim, policy, or any entity the brain might know about.',
        'parameters': {'type': 'object', 'properties': {'query': {'type': 'string', 'description': 'Natural language search query'}, 'type': {'type': 'string', 'description': 'Filter by page type: field, farmer, district, company, insurance_worker, claim, policy, season, crop, weather_station, equipment'}, 'limit': {'type': 'integer', 'description': 'Max results to return (default 10, max 100)'}}, 'required': ['query']},
    },
    'brain_graph_query': {
        'name': 'brain_graph_query',
        'description': "Walk the brain's typed-edge graph from a starting entity slug. Returns the network of related entities up to N hops out, with each link carrying a semantic edge type (field_in_district, claim_under_policy, crop_planted_in, policyholder, etc.). Use this for RELATIONAL questions: 'fields under this policy', 'claims in this district last season', 'who owns fields in Huye', 'what does Cyampirita connect to'. Returns ~4× more relevant results than search_brain on relational queries (GBrain BrainBench: 49.1% P@5 vs 17.8% without graph). For flat keyword/semantic lookup use search_brain. For temporal trajectory of a typed claim on one entity use brain_trajectory. PostGIS verifies geometric containment edges (field_in_district) via ST_Contains so the result is geometry-backed, not text-guessed.",
        'parameters': {'type': 'object', 'properties': {'slug': {'type': 'string', 'description': "Starting entity slug, e.g. 'fields/cyampirita', 'districts/huye', 'policies/bk-2025-q2'"}, 'depth': {'type': 'integer', 'description': 'Hops out from the starting slug (default 2, clamped to 1..5). Higher depth widens the network but slows the query.'}, 'edge_types': {'type': 'array', 'items': {'type': 'string'}, 'description': "Optional filter — only include links whose link_type is in this list, e.g. ['field_in_district', 'policy_covers_field']. Common edges: field_in_district, field_owned_by, field_under_policy, claim_on_field, claim_under_policy, policy_covers_field, intelligence_for_field, station_in_district, crop_planted_in, active_in_season."}}, 'required': ['slug']},
    },
    'brain_trajectory': {
        'name': 'brain_trajectory',
        'description': "Read the chronological history of a typed claim on a single entity, with regressions auto-flagged. Pulls from the ## Facts fence parsed into brain_facts: e.g. ndvi=0.65 validFrom:2026-05-15, then ndvi=0.41 validFrom:2026-05-29 surfaces as a regression because the value dropped > threshold. Use this for 'how has X changed for entity Y' questions where the user wants a time series, not a snapshot. Common keys: ndvi, soil_moisture, anomaly_score, crop, yield_kg_per_ha. Returns trajectory entries with valid_from, value, status (active/superseded/forgotten), and regression_flag.",
        'parameters': {'type': 'object', 'properties': {'slug': {'type': 'string', 'description': "Entity slug, e.g. 'fields/cyampirita', 'farmers/jean-bosco'"}, 'key': {'type': 'string', 'description': "Typed-claim key to walk, e.g. 'ndvi', 'soil_moisture', 'crop'"}, 'limit': {'type': 'integer', 'description': 'Max entries to return (default 50, max 500)'}}, 'required': ['slug', 'key']},
    },
    'get_entity': {
        'name': 'get_entity',
        'description': "Get a specific brain page by its slug. Returns the full compiled truth, recent timeline entries, tags, and linked entities. Use when the user asks about a specific known entity like 'field-gasabo-001' or 'farmer-uwimana'.",
        'parameters': {'type': 'object', 'properties': {'slug': {'type': 'string', 'description': "The entity slug (e.g. 'field-gasabo-001', 'farmer-uwimana')"}}, 'required': ['slug']},
    },
    'add_observation': {
        'name': 'add_observation',
        'description': "Add a timeline observation to a brain page. Use when the user reports a field visit, observation, measurement, or event that should be recorded in an entity's history. The brain grows with every observation.",
        'parameters': {'type': 'object', 'properties': {'slug': {'type': 'string', 'description': 'The entity slug to add the observation to'}, 'summary': {'type': 'string', 'description': 'Short summary of the observation'}, 'detail': {'type': 'string', 'description': 'Detailed description (optional)'}, 'date': {'type': 'string', 'description': 'Date of the observation (YYYY-MM-DD). Default: today'}, 'source': {'type': 'string', 'description': "Source of the observation (e.g. 'field_visit', 'satellite', 'user_report'). Default: 'user_report'"}}, 'required': ['slug', 'summary']},
    },
    'search_location': {
        'name': 'search_location',
        'description': 'Search for a location by name and return its bounding box and coordinates. Use this when the user mentions a place name and you need geographic coordinates for satellite imagery or spectral index tools.',
        'parameters': {'type': 'object', 'properties': {'query': {'type': 'string', 'description': "Place name to search for, e.g. 'Musanze district, Rwanda' or 'Kigali'"}}, 'required': ['query'], 'additionalProperties': False},
    },
    'display_satellite_layer': {
        'name': 'display_satellite_layer',
        'description': 'Display satellite imagery (true color) on the map for a specific area and date range. Searches Earth Search for the best Sentinel-2 scene and adds it as a visible tile layer. Use this when the user wants to SEE satellite imagery on the map for a location.',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'west,south,east,north' in WGS84 coordinates, e.g. '29.44,-1.72,29.68,-1.50'"}, 'date_from': {'type': 'string', 'description': "Start date in ISO 8601 format, e.g. '2025-01-01'"}, 'date_to': {'type': 'string', 'description': "End date in ISO 8601 format, e.g. '2025-01-31'"}, 'layer_name': {'type': 'string', 'description': "Display name for the map layer, e.g. 'Musanze TCI Jan 2025'"}}, 'required': ['bbox', 'date_from', 'date_to', 'layer_name'], 'additionalProperties': False},
    },
    'compute_spectral_index': {
        'name': 'compute_spectral_index',
        'description': 'Compute a spectral index (NDVI, NDWI, or NBR) over an area and display it on the map with a colormap. Returns area statistics (mean, std, min, max). Use this for vegetation health analysis (NDVI), water/flood detection (NDWI), or burn severity mapping (NBR). Always call search_location first to get the bbox. WHEN TO USE: the user wants to SEE NDVI/NDWI/NBR as a coloured layer on the map. WHEN NOT TO USE: numbers/stats only — use get_field_health or get_ndvi_stats. This tool renders; it does not return tabular metrics.',
        'parameters': {'type': 'object', 'properties': {'bbox': {'type': 'string', 'description': "Bounding box as 'west,south,east,north' in WGS84 coordinates"}, 'index': {'type': 'string', 'enum': ['ndvi', 'ndwi', 'nbr'], 'description': "Spectral index to compute: 'ndvi' (vegetation health), 'ndwi' (water/flooding), or 'nbr' (burn severity)"}, 'date_from': {'type': 'string', 'description': "Start date in ISO 8601 format, e.g. '2025-01-01'"}, 'date_to': {'type': 'string', 'description': "End date in ISO 8601 format, e.g. '2025-01-31'"}, 'layer_name': {'type': 'string', 'description': "Display name for the map layer, e.g. 'NDVI Musanze Jan 2025'"}}, 'required': ['bbox', 'index', 'date_from', 'date_to', 'layer_name'], 'additionalProperties': False},
    },
    'analyze_rgb_field': {
        'name': 'analyze_rgb_field',
        'description': 'Analyze a user-uploaded RGB visual orthophoto for greenness and field coverage. Computes GRVI (Green-Red Vegetation Index) which is the only vegetation index derivable from RGB without a near-infrared band — about 70% as informative as true NDVI for distinguishing healthy from stressed canopy. Reports valid coverage in hectares (alpha-mask aware), GRVI mean / std / percentiles, and a coarse verdict (lush/healthy/moderate/sparse/bare). Use this for RGB-only drone orthos when the user asks about field coverage or visible greenness. ALWAYS prefer interpret_raster_health when the layer has a true NDVI band — true NDVI is more accurate. This tool is the honest fallback for RGB-only data.',
        'parameters': {'type': 'object', 'properties': {'layer_id': {'description': 'The layer_id of the user-uploaded RGB visual orthophoto (3-band ortho, no NIR).', 'title': 'Layer Id', 'type': 'string'}, 'polygon_geojson': {'description': "GeoJSON Polygon string defining the field area, OR empty string '' to analyze the whole raster.", 'title': 'Polygon Geojson', 'type': 'string'}, 'red_band': {'description': 'Which band contains the Red channel (1-indexed). For typical RGB drone orthos, Red is band 1. For BGR-ordered exports it may be band 3.', 'title': 'Red Band', 'type': 'integer'}, 'green_band': {'description': 'Which band contains the Green channel (1-indexed). For typical RGB drone orthos, Green is band 2.', 'title': 'Green Band', 'type': 'integer'}}, 'required': ['layer_id', 'polygon_geojson', 'red_band', 'green_band']},
    },
    'compare_rasters': {
        'name': 'compare_rasters',
        'description': "Compare two user-uploaded NDVI rasters of the same field at different times to detect change. Method 3: per-pixel NDVI diff at downsampled resolution + crop-stage-aware expected delta + CHIRPS rainfall context. Returns: time interval in days, observed mean NDVI delta, expected delta given crop stage transitions, anomaly (observed - expected), rainfall between captures, area declining significantly, and a verdict (no_significant_change / expected_growth / mild_decline / drought_signature / harvest_pattern / suspicious_pattern). Refuses if bounds don't overlap or either layer is RGB-only. The keystone tool for insurance change detection.",
        'parameters': {'type': 'object', 'properties': {'layer_id_a': {'description': "The first user-uploaded NDVI raster (typically the EARLIER flight or 'before' timepoint).", 'title': 'Layer Id A', 'type': 'string'}, 'layer_id_b': {'description': "The second user-uploaded NDVI raster (typically the LATER flight or 'after' timepoint). Must overlap with layer_id_a.", 'title': 'Layer Id B', 'type': 'string'}, 'band': {'description': 'Which band contains NDVI (1-indexed). For single-band NDVI use 1; for typical 4-band drone NDVI export use 2.', 'title': 'Band', 'type': 'integer'}, 'crop': {'description': "The crop in the field — used to look up the expected NDVI delta between the two captures' growth stages. Supported: 'maize', 'beans', 'rice', 'sorghum', 'wheat'. Pass 'unknown' if no crop information.", 'title': 'Crop', 'type': 'string'}}, 'required': ['layer_id_a', 'layer_id_b', 'band', 'crop']},
    },
    'compute_zonal_stats': {
        'name': 'compute_zonal_stats',
        'description': 'Compute pixel statistics (mean, min, max, std, p10, p50, p90) over a polygon area within a user-uploaded raster, on a specified band. NoData pixels are excluded from the calculation and the percentage of valid pixels is reported. If polygon_geojson is empty, computes stats over the whole raster. Use this whenever you need numerical stats from a user\'s drone or NDVI raster — for example, "what\'s the average NDVI in this field?". Do NOT use for satellite stats (those have their own tools).',
        'parameters': {'type': 'object', 'properties': {'layer_id': {'description': 'The layer_id of the user-uploaded raster.', 'title': 'Layer Id', 'type': 'string'}, 'polygon_geojson': {'description': "A GeoJSON Polygon string defining the area to analyze (use this if the user drew a polygon or wants stats over a specific field). Pass empty string '' to analyze the whole raster.", 'title': 'Polygon Geojson', 'type': 'string'}, 'band': {'description': 'Which raster band to analyze (1-indexed). For typical 4-band drone NDVI exports, NDVI is in band 2. For dedicated single-band NDVI rasters, use band 1. Default to 1 if uncertain.', 'title': 'Band', 'type': 'integer'}}, 'required': ['layer_id', 'polygon_geojson', 'band']},
    },
    'create_point_layer': {
        'name': 'create_point_layer',
        'description': 'Create a new point layer from coordinates. Use this when the user provides lat/lon coordinates and you need a layer to mark that location, buffer into a circle, or use as input for geoprocessing tools.',
        'parameters': {'type': 'object', 'properties': {'longitude': {'description': 'Longitude in decimal degrees (WGS84), e.g. 30.1127', 'title': 'Longitude', 'type': 'number'}, 'latitude': {'description': 'Latitude in decimal degrees (WGS84), e.g. -2.2321', 'title': 'Latitude', 'type': 'number'}, 'label': {'description': "Human-readable label for the point, e.g. 'Rusumo Falls'", 'title': 'Label', 'type': 'string'}}, 'required': ['longitude', 'latitude', 'label']},
    },
    'describe_user_raster': {
        'name': 'describe_user_raster',
        'description': "Describe a user-uploaded raster layer in plain language: bounds, area in hectares, band count, dimensions, file size, COG status, capture date if known. Performs a sanity check that this layer's geographic location is reasonable relative to other rasters in the same project (catches CRS errors where a Rwanda field gets georeferenced to Florida by a misconfigured drone export). Use this whenever the user asks ABOUT one of their uploaded rasters — drone orthophotos, NDVI rasters, multispectral tiffs. Do NOT use for satellite-data questions (use get_ndvi_stats or get_field_health for those).",
        'parameters': {'type': 'object', 'properties': {'layer_id': {'description': "The layer_id of the user-uploaded raster (starts with 'L', visible in the project's layer panel). Example: 'LwQ6VWK64bvL'.", 'title': 'Layer Id', 'type': 'string'}}, 'required': ['layer_id']},
    },
    'display_geojson_layer': {
        'name': 'display_geojson_layer',
        'description': "Display inline GeoJSON polygons on the map with categorical fill colors.\n\n    Use this when an analytical tool returns vector polygons (e.g. an insured\n    parcel boundary with a composite_score, stress-zone clusters with severity,\n    or AOI outlines). Pair with evaluate_insurance_trigger, find_stress_zones,\n    or any tool that produces polygon evidence the user should SEE.\n\n    The style_hint picks a categorical color ramp keyed off a property on each\n    feature (composite_score, ndvi_mean, severity). The frontend renders the\n    layer immediately and adds it to the user's layer panel.\n\n    Pattern: compute (returns polygons + scored properties) → display_geojson_layer\n    (paints them).",
        'parameters': {'type': 'object', 'properties': {'geojson': {'description': "Inline GeoJSON FeatureCollection or Feature as a JSON string. Each feature should carry the property used by the style_hint's color_property (e.g. 'composite_score' for insurance_composite_score, 'ndvi_mean' for field_health, 'severity' for stress_zones).", 'title': 'Geojson', 'type': 'string'}, 'layer_name': {'description': 'Human-readable name for this vector layer in the layers panel.', 'title': 'Layer Name', 'type': 'string'}, 'style_hint': {'description': 'Vector style preset. One of: insurance_composite_score, field_health, rgb_field_health, stress_zones, outline, water, flood_extent, similarity_score, food_security_ipc.', 'title': 'Style Hint', 'type': 'string'}, 'bbox': {'description': "Bounding box of the GeoJSON, as 'west,south,east,north' WGS84. Used for auto-zoom.", 'title': 'Bbox', 'type': 'string'}}, 'required': ['geojson', 'layer_name', 'style_hint', 'bbox']},
    },
    'display_layer': {
        'name': 'display_layer',
        'description': "Display any public Cloud-Optimized GeoTIFF on the map with a styled colormap.\n\n    This is the GENERIC display tool. Use it after computing or identifying a spatial\n    raster you want the user to SEE. Pair it with analytical tools that return a URL:\n    1. Call the analytical tool (e.g. get_soil_properties returns iSDAsoil COG URL).\n    2. Call display_layer with that URL + a style_hint that names the domain.\n\n    The frontend renders the layer immediately and adds it to the user's layer panel\n    so they can toggle it on/off.\n\n    Style hints map to colormaps and value ranges defined in STYLE_PRESETS. Pick the\n    one that matches the data's domain — soil_nitrogen for N maps, ndvi for NDVI,\n    drought_severity for VCI, etc.",
        'parameters': {'type': 'object', 'properties': {'asset_url': {'description': "Public HTTPS URL of a Cloud-Optimized GeoTIFF (COG). Examples: 'https://isdasoil.s3.amazonaws.com/soil_data/nitrogen_total/nitrogen_total.tif', 'https://earth-search.aws.element84.com/...../B04.tif'. GeoJSON URLs and S3 protocol URLs are not yet supported in this version.", 'title': 'Asset Url', 'type': 'string'}, 'layer_name': {'description': "Human-readable layer name shown in the layers panel, e.g. 'Soil Nitrogen — Cyampirita'", 'title': 'Layer Name', 'type': 'string'}, 'style_hint': {'description': 'Style preset that picks the colormap and value range. One of: ndvi, ndwi, nbr, visual, ndvi_band, ndre_band, soil_nitrogen, soil_phosphorus, soil_potassium, soil_ph, soil_organic_carbon, soil_clay, soil_sand, anomaly_zscore, drought_severity, soil_moisture, evapotranspiration, temperature, rainfall, sar_backscatter_db.', 'title': 'Style Hint', 'type': 'string'}, 'bbox': {'description': "Bounding box of the area to display, as 'west,south,east,north' in WGS84. Used for auto-zoom.", 'title': 'Bbox', 'type': 'string'}, 'band_index': {'description': '1-based band index for single-band rasters (use 1 for most soil COGs and z-score rasters).', 'title': 'Band Index', 'type': 'integer'}}, 'required': ['asset_url', 'layer_name', 'style_hint', 'bbox', 'band_index']},
    },
    'evaluate_insurance_trigger': {
        'name': 'evaluate_insurance_trigger',
        'description': "Evaluate parametric insurance trigger conditions on a user's drone NDVI flights. Composes compare_rasters (change detection) + zonal stats on the 'after' raster (current absolute health) + a per-crop-stage threshold table. Computes a 0-100 composite_score across 4 weighted signals (absolute health, NDVI decline vs expected, area declining significantly, drought context from rainfall) and returns triggered=True if score >= 60. Returns triggered (bool), composite_score (0-100), per-signal status with thresholds, payout_recommendation, plus full underlying compare_rasters evidence. ALWAYS use this when the user asks 'should this claim pay out?', 'is the trigger fired?', 'evaluate the insurance', or any parametric-trigger question on drone NDVI data. Source='drone' — for satellite-based triggers use get_insurance_intelligence.",
        'parameters': {'type': 'object', 'properties': {'layer_id_before': {'description': "The layer_id of the EARLIER drone NDVI raster ('before' / baseline). For policy onboarding without a prior flight, pass the same id as layer_id_after — degenerate case will be reported.", 'title': 'Layer Id Before', 'type': 'string'}, 'layer_id_after': {'description': "The layer_id of the LATER drone NDVI raster ('after' / current claim flight).", 'title': 'Layer Id After', 'type': 'string'}, 'band': {'description': 'Which band contains NDVI (1-indexed). For single-band NDVI use 1; for typical 4-band drone NDVI export use 2.', 'title': 'Band', 'type': 'integer'}, 'crop': {'description': "Crop in the field. Supported: 'maize', 'beans', 'rice', 'sorghum', 'wheat'. Pass 'unknown' if not specified — accuracy will be reduced.", 'title': 'Crop', 'type': 'string'}, 'polygon_geojson': {'description': "GeoJSON Polygon string defining the insured field boundary, OR empty string '' to use the whole 'after' raster. Used to compute the current absolute-NDVI signal.", 'title': 'Polygon Geojson', 'type': 'string'}}, 'required': ['layer_id_before', 'layer_id_after', 'band', 'crop', 'polygon_geojson']},
    },
    'find_similar_tiles': {
        'name': 'find_similar_tiles',
        'description': "Find tiles visually similar to a point in a user's raster, across all of that user's other rasters. Powered by Clay v1.5 visual embeddings in Qdrant. Use this when the user asks 'find other fields that look like this stressed patch', 'have we seen this damage pattern in any other flight?', 'show me similar areas across my orthophotos', or any cross-flight visual similarity question. Returns top-K similar tiles ranked by cosine similarity (1.0 = identical, lower = less similar). For exact-match analysis at a single point use read_pixel_at; for whole-field health verdict use interpret_raster_health. Only works on rgb_visual rasters that have been embedded (orthophotos auto-embed after COG conversion completes).",
        'parameters': {'type': 'object', 'properties': {'layer_id': {'description': 'The layer_id of the user-uploaded raster the query point lives in.', 'title': 'Layer Id', 'type': 'string'}, 'longitude': {'description': 'Longitude in WGS84 decimal degrees of the query point.', 'title': 'Longitude', 'type': 'number'}, 'latitude': {'description': 'Latitude in WGS84 decimal degrees of the query point.', 'title': 'Latitude', 'type': 'number'}, 'top_k': {'description': 'How many similar tiles to return. Use 5-10 for a quick scan, up to 50 for a thorough audit. Pass 0 to use the default of 10.', 'title': 'Top K', 'type': 'integer'}}, 'required': ['layer_id', 'longitude', 'latitude', 'top_k']},
    },
    'find_stress_zones': {
        'name': 'find_stress_zones',
        'description': 'Find connected clusters of low-NDVI pixels in a user-uploaded NDVI raster — the spatial answer to "where is the stress in my field?". Returns a list of stress zones with each zone\'s center coordinate, area in hectares, mean NDVI inside the cluster, and severity label (severe/moderate/mild). Refuses non-NDVI rasters with a pointer to the right tool. Useful for: locating drought patches, finding diseased zones, prioritizing field walks. For a single overall verdict use interpret_raster_health; for a histogram use get_value_distribution.',
        'parameters': {'type': 'object', 'properties': {'layer_id': {'description': 'The layer_id of a user-uploaded NDVI raster (single-band float, or band 2 of a 4-band drone NDVI export).', 'title': 'Layer Id', 'type': 'string'}, 'band': {'description': 'Which band contains NDVI (1-indexed). For single-band NDVI use 1; for typical 4-band drone NDVI export use 2.', 'title': 'Band', 'type': 'integer'}, 'ndvi_threshold': {'description': 'Pixels with NDVI BELOW this threshold are considered stressed. Reasonable defaults: 0.30 for severe stress, 0.40 for moderate. For a vegetative-stage maize field expecting NDVI ~0.55-0.70, use 0.40 to flag clear stress patches.', 'title': 'Ndvi Threshold', 'type': 'number'}, 'min_area_ha': {'description': 'Skip stress clusters smaller than this many hectares. Use 0.5 to filter out noise patches; use 0.1 for fine-grained analysis. Connected stress patches below this size are not reported.', 'title': 'Min Area Ha', 'type': 'number'}}, 'required': ['layer_id', 'band', 'ndvi_threshold', 'min_area_ha']},
    },
    'get_value_distribution': {
        'name': 'get_value_distribution',
        'description': 'Compute the value distribution (histogram + percentiles) of a raster band over a polygon (or whole raster). Returns: bin edges, bin counts, percentiles (5/10/25/50/75/90/95), mean, std, min, max, mode-bin. Skips NoData. Use this when the user asks about the spread, distribution, or variability of pixel values — for example, "what\'s the NDVI distribution across this field?", "are values bimodal?", "what\'s the worst 10% of pixels?". For a single number, use compute_zonal_stats. For a verdict on the field, use interpret_raster_health.',
        'parameters': {'type': 'object', 'properties': {'layer_id': {'description': 'The layer_id of the user-uploaded raster.', 'title': 'Layer Id', 'type': 'string'}, 'band': {'description': 'Which band to sample (1-indexed). For NDVI in 4-band drone exports use 2; for single-band NDVI use 1.', 'title': 'Band', 'type': 'integer'}, 'polygon_geojson': {'description': "GeoJSON Polygon string to constrain the histogram, OR empty string '' to sample the whole raster.", 'title': 'Polygon Geojson', 'type': 'string'}, 'bins': {'description': 'Number of histogram bins. Use 20 as a default for human-readable display; up to 100 for fine analysis.', 'title': 'Bins', 'type': 'integer'}}, 'required': ['layer_id', 'band', 'polygon_geojson', 'bins']},
    },
    'interpret_raster_health': {
        'name': 'interpret_raster_health',
        'description': 'Interpret pixel data from a user-uploaded NDVI raster as a farmer-language verdict on field health, given a crop type, growth stage, and field polygon. Composes describe_user_raster (for metadata + CRS sanity) plus compute_zonal_stats (for pixel statistics) plus the agricultural crop calendar (to map capture date to growth stage) plus a curated NDVI threshold table (to convert numbers to verdicts). Returns a verdict (exceptional / healthy / moderate_stress / severe_stress) plus evidence and recommended action — NOT raw band statistics. ALWAYS use this when the user asks about the health of a field they have a drone NDVI or NDVI raster for. Do NOT use for satellite-only questions (use get_field_health for those).',
        'parameters': {'type': 'object', 'properties': {'layer_id': {'description': 'The layer_id of the user-uploaded NDVI raster (drone export, computed NDVI from satellite, etc.).', 'title': 'Layer Id', 'type': 'string'}, 'crop': {'description': "The crop in the field. Supported: 'maize', 'beans', 'rice', 'sorghum', 'wheat'. Pass 'unknown' if the user hasn't specified — defaults will be used.", 'title': 'Crop', 'type': 'string'}, 'band': {'description': 'Which band of the raster contains NDVI (1-indexed). For typical drone exports with 4 bands [R, NDVI, NDRE, alpha], use band=2. For dedicated single-band NDVI rasters, use band=1. Default to 1 if uncertain.', 'title': 'Band', 'type': 'integer'}, 'polygon_geojson': {'description': "GeoJSON Polygon string defining the field boundary, OR empty string '' to evaluate the whole raster.", 'title': 'Polygon Geojson', 'type': 'string'}, 'captured_date': {'description': "Date the imagery was captured, YYYY-MM-DD format. Pass empty string '' if unknown — today's date will be used as an approximation (less accurate for growth-stage inference).", 'title': 'Captured Date', 'type': 'string'}}, 'required': ['layer_id', 'crop', 'band', 'polygon_geojson', 'captured_date']},
    },
    'read_pixel_at': {
        'name': 'read_pixel_at',
        'description': 'Read the per-band raw pixel value at a specific lon/lat location in a user-uploaded raster. Validates the point falls inside the layer\'s bounds first — if the user clicks at Rwanda coordinates against a Florida-georeferenced raster, returns a clear "outside bounds" error instead of silently returning NoData. Use this when the user clicks a specific spot on the map and asks "what\'s the value here?". For statistics over an area, use compute_zonal_stats. For a verdict on the whole field, use interpret_raster_health or analyze_rgb_field.',
        'parameters': {'type': 'object', 'properties': {'layer_id': {'description': 'The layer_id of the user-uploaded raster.', 'title': 'Layer Id', 'type': 'string'}, 'longitude': {'description': 'Longitude in WGS84 decimal degrees (e.g. 30.4245 for Rwanda).', 'title': 'Longitude', 'type': 'number'}, 'latitude': {'description': 'Latitude in WGS84 decimal degrees (e.g. -1.6970 for Rwanda).', 'title': 'Latitude', 'type': 'number'}}, 'required': ['layer_id', 'longitude', 'latitude']},
    },
    # render_map_snapshot intentionally removed (2026-05-18, feat/hermes-gateway-api-server-pivot).
    # The schema was orphaned — no handler exists in pydantic_tools.py, legacy_tool_shim.py,
    # or anywhere else in src/. Advertising it to the LLM caused tool-call → 404 →
    # "Sorry I can't" loops. When the snapshot delivery pipeline (MinIO upload +
    # 'mundi:render_snapshot' Redis pubsub for the whatsapp/telegram senders) actually
    # ships, re-add the schema in the SAME PR that adds the handler in legacy_tool_shim.
    'zoom_to_bounds': {
        'name': 'zoom_to_bounds',
        'description': "Zoom the map to a specific bounding box in WGS84 coordinates. This will save the user's current zoom location to history and navigate to the new bounds.",
        'parameters': {'type': 'object', 'properties': {'bounds': {'description': 'Bounding box in WGS84 format [xmin, ymin, xmax, ymax]', 'items': {'type': 'number'}, 'maxItems': 4, 'minItems': 4, 'title': 'Bounds', 'type': 'array'}, 'zoom_description': {'description': 'Complete message to display to the user while zooming, e.g. "Zooming to 39 selected parcels near Ohio"', 'title': 'Zoom Description', 'type': 'string'}}, 'required': ['bounds', 'zoom_description']},
    },
}
