import { apiFetch } from '@mundi/ee';
import { useMutation } from '@tanstack/react-query';
import { ChevronLeft, ChevronRight, FileText, Plus, SignalHigh, SignalLow, Upload } from 'lucide-react';
import { Map as MLMap } from 'maplibre-gl';
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ReadyState } from 'react-use-websocket';
import { toast } from 'sonner';

import EditableTitle from '@/components/EditableTitle';
import { LayerListItem } from '@/components/LayerListItem';
import UploadDocument from '@/components/UploadDocument';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import type { PaintOverrides } from '../hooks/useLayerPaintOverrides';
import type { ErrorEntry } from '../lib/frontend-types';
import type { EphemeralAction, MapData, MapLayer, MapProject } from '../lib/types';

interface UploadingFile {
  id: string;
  file: File;
  progress: number;
  status: 'uploading' | 'completed' | 'error';
  phase?: string;
  error?: string;
}

interface LayerListProps {
  project: MapProject;
  currentMapData: MapData;
  mapRef: React.RefObject<MLMap | null>;
  openDropzone: () => void;
  activeActions: EphemeralAction[];
  readyState: number;
  isInConversation: boolean;
  setShowAttributeTable: (show: boolean) => void;
  setSelectedLayer: (layer: MapLayer | null) => void;
  updateMapData: () => void;
  layerSymbols: { [layerId: string]: JSX.Element };
  zoomHistory: Array<{ bounds: [number, number, number, number] }>;
  zoomHistoryIndex: number;
  setZoomHistoryIndex: React.Dispatch<React.SetStateAction<number>>;
  uploadingFiles?: UploadingFile[];
  hiddenLayerIDs: string[];
  toggleLayerVisibility: (layerId: string) => void;
  errors: ErrorEntry[];
  loadingLayerIDs?: string[];
  paintOverrides?: PaintOverrides;
  onLayerOpacityChange?: (layerId: string, opacity: number) => void;
  onLayerColorChange?: (layerId: string, color: string) => void;
}

const LayerList: React.FC<LayerListProps> = ({
  project,
  currentMapData,
  mapRef,
  openDropzone,
  readyState,
  activeActions,
  isInConversation,
  setShowAttributeTable,
  setSelectedLayer,
  updateMapData,
  layerSymbols,
  zoomHistory,
  zoomHistoryIndex,
  setZoomHistoryIndex,
  uploadingFiles,
  hiddenLayerIDs,
  toggleLayerVisibility,
  errors,
  loadingLayerIDs,
  paintOverrides,
  onLayerOpacityChange,
  onLayerColorChange,
}) => {
  const navigate = useNavigate();

  // Helper function to get errors for a specific source/layer ID
  const getLayerErrors = (layerId: string): ErrorEntry[] => {
    return errors.filter((error) => error.sourceId === layerId);
  };

  // Component to render legend symbol for a layer
  const LayerLegendSymbol = ({ layerDetails }: { layerDetails: MapLayer; isLoading: boolean }) => {
    // Return cached symbol first (generated by legend-symbol-ts after style loads)
    if (layerSymbols[layerDetails.id]) {
      return layerSymbols[layerDetails.id];
    }
    // Fallback symbols by layer type when legend-symbol-ts hasn't resolved yet
    // (raster sources use prefixed IDs like cog-source-{id} that don't match exact lookup)
    if (layerDetails.type === 'raster') {
      return (
        <div
          className="w-4 h-4 rounded-sm border border-gray-500 flex-shrink-0"
          style={{ background: 'linear-gradient(135deg, #4ade80 0%, #22d3ee 50%, #818cf8 100%)' }}
          title="Raster layer"
        />
      );
    }
    if (layerDetails.type === 'point_cloud') {
      return (
        <div className="w-4 h-4 flex items-center justify-center flex-shrink-0">
          <div className="w-2 h-2 rounded-full bg-cyan-400 shadow-sm" title="Point cloud layer" />
        </div>
      );
    }
    if (layerDetails.type === 'postgis') {
      const geometryType = (layerDetails.geometry_type ?? layerDetails.metadata?.geometry_type ?? '').toLowerCase();
      if (geometryType.includes('polygon')) {
        return (
          <div
            className="w-4 h-4 rounded-sm flex-shrink-0"
            style={{ backgroundColor: 'rgba(255, 77, 77, 0.28)', border: '2px solid #ff2d2d' }}
            title="PostGIS polygon layer"
          />
        );
      }
      if (geometryType.includes('line')) {
        return (
          <div className="w-4 h-4 flex items-center flex-shrink-0" title="PostGIS line layer">
            <div className="h-0.5 w-full rounded-full bg-red-400" />
          </div>
        );
      }
    }
    // Vector layer — symbol not yet loaded, show neutral placeholder
    return <div className="w-4 h-4 rounded-sm bg-gray-600 opacity-60 flex-shrink-0" title="Vector layer" />;
  };
  const [showUploadDocDialog, setShowUploadDocDialog] = useState(false);

  const renameMutation = useMutation({
    mutationFn: async ({ layerId, newName }: { layerId: string; newName: string }) => {
      const response = await apiFetch(`/api/layer/${layerId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ name: newName }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ detail: response.statusText }));
        const d = errorData.detail;
        throw new Error(typeof d === 'string' ? d : d ? JSON.stringify(d) : response.statusText);
      }

      return response.json();
    },
    onSuccess: () => {
      updateMapData();
      toast.success('Layer renamed');
    },
    onError: (error) => {
      console.error('Error renaming layer:', error);
      toast.error(`Error renaming layer: ${error.message}`);
    },
  });

  return (
    <Card className="absolute top-4 left-4 max-h-[60vh] overflow-auto py-2 rounded-sm border-0 gap-2 max-w-72 w-full">
      <CardHeader className="px-2">
        <CardTitle className="text-base flex justify-between items-center gap-2">
          <div className="flex items-center gap-2">
            <Tooltip>
              <TooltipTrigger>
                {!isInConversation || readyState === ReadyState.OPEN ? (
                  <span className="text-green-300 inline-block">
                    <SignalHigh />
                  </span>
                ) : (
                  <span className="text-red-300 inline-block">
                    <SignalLow />
                  </span>
                )}
              </TooltipTrigger>
              <TooltipContent>
                <div className="text-sm flex space-x-2">
                  {isInConversation && (
                    <div className={readyState === ReadyState.OPEN ? 'text-green-300' : 'text-red-300'}>
                      chat:{' '}
                      {readyState === ReadyState.OPEN ? (
                        <SignalHigh className="inline-block h-4 w-4" />
                      ) : (
                        <SignalLow className="inline-block h-4 w-4" />
                      )}
                    </div>
                  )}
                </div>
              </TooltipContent>
            </Tooltip>
            <EditableTitle projectId={currentMapData.project_id} title={project?.title} placeholder="Enter map title here" />
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="px-0">
        {(currentMapData.layers?.length ?? 0) > 0 ? (
          <ul className="text-sm">
            {(currentMapData.layers ?? []).map((layerDetails: MapLayer) => {
              // Check if this layer has an active action
              const hasActiveAction = activeActions.some((action) => action.layer_id === layerDetails.id);
              const num_highlighted = 0;

              const sridDisplay = layerDetails.metadata?.original_srid ? `EPSG:${layerDetails.metadata.original_srid}` : undefined;

              const normalText =
                layerDetails.type === 'raster'
                  ? 'Raster'
                  : layerDetails.type === 'point_cloud'
                    ? 'Point Cloud'
                    : num_highlighted > 0
                      ? `${num_highlighted} / ${layerDetails.feature_count ?? '—'}`
                      : String(layerDetails.feature_count ?? '—');

              const hoverText = sridDisplay;

              // Check for errors associated with this layer
              const layerErrors = getLayerErrors(layerDetails.id);
              const hasErrors = layerErrors.length > 0;

              const getNameClassName = () => {
                if (hiddenLayerIDs.includes(layerDetails.id)) {
                  return 'line-through text-gray-400';
                }
                if (hasErrors) {
                  return 'text-red-300';
                }
                return '';
              };

              // Create title text from error messages if any
              const errorTitle = hasErrors ? layerErrors.map((error) => error.message).join(' | ') : undefined;

              return (
                <li key={layerDetails.id}>
                  <LayerListItem
                    name={layerDetails.name}
                    nameClassName={getNameClassName()}
                    isActive={hasActiveAction}
                    hoverText={hoverText}
                    normalText={normalText}
                    legendSymbol={
                      <LayerLegendSymbol layerDetails={layerDetails} isLoading={!!loadingLayerIDs?.includes(layerDetails.id)} />
                    }
                    isLoading={!!loadingLayerIDs?.includes(layerDetails.id)}
                    layerId={layerDetails.id}
                    isVisible={!hiddenLayerIDs.includes(layerDetails.id)}
                    title={errorTitle}
                    opacity={paintOverrides?.[layerDetails.id]?.opacity}
                    onOpacityChange={onLayerOpacityChange}
                    currentColor={paintOverrides?.[layerDetails.id]?.color}
                    onColorChange={layerDetails.type === 'vector' || layerDetails.type === 'postgis' ? onLayerColorChange : undefined}
                    onToggleVisibility={(layerId) => {
                      toggleLayerVisibility(layerId);
                    }}
                    onRename={(layerId, newName) => {
                      renameMutation.mutate({ layerId, newName });
                    }}
                    dropdownActions={{
                      'zoom-to-layer': {
                        label: 'Zoom to layer',
                        disabled: false,
                        action: async (layerId) => {
                          const layer = currentMapData.layers?.find((l) => l.id === layerId);
                          if (!layer) {
                            toast.error('Layer not found');
                            return;
                          }
                          let bounds = layer.bounds;
                          // If bounds missing, fetch/compute them from the backend
                          if (!bounds || bounds.length !== 4) {
                            try {
                              const res = await apiFetch(`/api/layer/${layerId}/bounds`);
                              if (res.ok) {
                                const data = await res.json();
                                bounds = data.bounds;
                                // Update the cached layer data so next click is instant
                                if (bounds && bounds.length === 4) {
                                  layer.bounds = bounds;
                                }
                              }
                            } catch {
                              // fall through to error below
                            }
                          }
                          if (bounds && bounds.length === 4 && mapRef.current) {
                            mapRef.current.fitBounds(
                              [
                                [bounds[0], bounds[1]],
                                [bounds[2], bounds[3]],
                              ],
                              { padding: 50, animate: true },
                            );
                            toast.success('Zoomed to layer');
                          } else {
                            toast.info('Layer bounds not available for zoom.');
                          }
                        },
                      },
                      'view-attributes': {
                        label: 'View attributes',
                        disabled: false,
                        action: (layerId) => {
                          const layer = currentMapData.layers?.find((l) => l.id === layerId);
                          if (!layer) {
                            toast.error('Layer not found');
                            return;
                          }
                          setSelectedLayer(layer);
                          setShowAttributeTable(true);
                        },
                      },
                      'delete-layer': {
                        label: 'Delete layer',
                        action: (layerId) => {
                          apiFetch(`/api/maps/${currentMapData.map_id}/layer/${layerId}`, {
                            method: 'DELETE',
                            headers: { 'Content-Type': 'application/json' },
                          })
                            .then((response) => {
                              if (response.ok) {
                                return response.json();
                              } else {
                                throw new Error(`Failed to delete layer: ${response.statusText}`);
                              }
                            })
                            .then((data) => {
                              toast.success(`Layer successfully removed! Navigating to new map...`);
                              // Navigate to the new child map if dag_child_map_id is present
                              if (data.dag_child_map_id) {
                                setTimeout(() => {
                                  navigate(`/project/${project.id}/${data.dag_child_map_id}`);
                                }, 1000);
                              } else {
                                // Fallback: reload the page
                                window.location.reload();
                              }
                            })
                            .catch((err) => {
                              console.error('Error deleting layer:', err);
                              toast.error(`Error deleting layer: ${err.message}`);
                            });
                        },
                      },
                    }}
                  />
                </li>
              );
            })}
          </ul>
        ) : (
          <p className="text-sm text-slate-500 px-2">No layers to display.</p>
        )}

        {/* Upload Progress section */}
        {uploadingFiles && uploadingFiles.length > 0 && (
          <>
            <div className="flex items-center px-2 py-2">
              <div className="flex-1 h-px bg-gray-300 dark:bg-gray-600"></div>
              <span className="px-3 text-xs font-medium text-gray-600 dark:text-gray-400">UPLOADING</span>
              <div className="flex-1 h-px bg-gray-300 dark:bg-gray-600"></div>
            </div>
            <ul className="space-y-2 text-sm px-2">
              {uploadingFiles.map((uploadingFile) => (
                <li key={uploadingFile.id} className="border border-gray-200 dark:border-gray-700 rounded-lg p-2">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">{uploadingFile.file.name}</span>
                    <span className="text-xs text-gray-500 dark:text-gray-400 flex-shrink-0">
                      {uploadingFile.status === 'uploading' && `${uploadingFile.progress}%`}
                      {uploadingFile.status === 'completed' && '✓'}
                      {uploadingFile.status === 'error' && '✗'}
                    </span>
                  </div>

                  {uploadingFile.status === 'uploading' && (
                    <>
                      <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-1.5">
                        <div
                          className="bg-blue-600 h-1.5 rounded-full transition-all duration-300"
                          style={{ width: `${uploadingFile.progress}%` }}
                        />
                      </div>
                      {uploadingFile.phase && (
                        <div className="mt-1 text-xs text-gray-500 dark:text-gray-400 truncate">{uploadingFile.phase}</div>
                      )}
                    </>
                  )}

                  {uploadingFile.status === 'completed' && (
                    <div className="text-xs text-green-600 dark:text-green-400">Upload completed</div>
                  )}

                  {uploadingFile.status === 'error' && (
                    <div className="text-xs text-red-600 dark:text-red-400">{uploadingFile.error || 'Upload failed'}</div>
                  )}
                </li>
              ))}
            </ul>
          </>
        )}
      </CardContent>
      <CardFooter className="flex justify-between items-center px-2">
        <div className="flex items-center gap-1">
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  size="sm"
                  variant="ghost"
                  className="p-0.5 hover:cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-600"
                  disabled={zoomHistoryIndex <= 0}
                  onClick={() => {
                    if (zoomHistoryIndex > 0 && mapRef.current) {
                      const newIndex = zoomHistoryIndex - 1;
                      const historyItem = zoomHistory[newIndex];
                      if (historyItem?.bounds && historyItem.bounds.length === 4) {
                        const targetBounds = historyItem.bounds;
                        mapRef.current.fitBounds(
                          [
                            [targetBounds[0], targetBounds[1]],
                            [targetBounds[2], targetBounds[3]],
                          ],
                          { animate: true },
                        );
                        setZoomHistoryIndex(newIndex);
                      } else {
                        console.error('Previous zoom - invalid historyItem or bounds:', historyItem);
                      }
                    }
                  }}
                >
                  <ChevronLeft className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p>Previous location</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
          <span className="text-xs text-slate-500 dark:text-gray-400">Zoom</span>
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  size="sm"
                  variant="ghost"
                  className="p-0.5 hover:cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-600"
                  disabled={zoomHistoryIndex >= zoomHistory.length - 1}
                  onClick={() => {
                    if (zoomHistoryIndex < zoomHistory.length - 1 && mapRef.current) {
                      const newIndex = zoomHistoryIndex + 1;
                      const historyItem = zoomHistory[newIndex];
                      if (historyItem?.bounds && historyItem.bounds.length === 4) {
                        const targetBounds = historyItem.bounds;
                        mapRef.current.fitBounds(
                          [
                            [targetBounds[0], targetBounds[1]],
                            [targetBounds[2], targetBounds[3]],
                          ],
                          { animate: true },
                        );
                        setZoomHistoryIndex(newIndex);
                      } else {
                        console.error('Next zoom - invalid historyItem or bounds:', historyItem);
                      }
                    }
                  }}
                >
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p>Next location</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        <div className="flex items-center gap-1">
          <TooltipProvider>
            <DropdownMenu>
              <Tooltip>
                <TooltipTrigger asChild>
                  <DropdownMenuTrigger asChild>
                    <Button size="sm" variant="ghost" className="p-0.5 hover:cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-600">
                      <Plus className="h-4 w-4" />
                    </Button>
                  </DropdownMenuTrigger>
                </TooltipTrigger>
                <TooltipContent>
                  <p>Add data</p>
                </TooltipContent>
              </Tooltip>
              {/* MVP (Roger, 2026-10-05): drone files first, plus documents for Sage. Satellite data
                  comes through Sage; connectors for GIS teams (WFS, ESRI, PostGIS, Sheets) are not offered. */}
              <DropdownMenuContent align="end" className="w-72">
                <DropdownMenuItem onClick={openDropzone} className="cursor-pointer items-start">
                  <Upload className="h-4 w-4 mr-2 mt-0.5 shrink-0" />
                  <span>
                    <span className="block">Upload drone or map files</span>
                    <span className="block text-xs text-muted-foreground">
                      Orthophoto (GeoTIFF), field shapes (KML, GeoJSON, zipped Shapefile) or points (CSV)
                    </span>
                  </span>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => setShowUploadDocDialog(true)} className="cursor-pointer items-start">
                  <FileText className="h-4 w-4 mr-2 mt-0.5 shrink-0" />
                  <span>
                    <span className="block">Add documents for Sage</span>
                    <span className="block text-xs text-muted-foreground">Reports, policies or guides Sage can read and quote</span>
                  </span>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </TooltipProvider>
        </div>

        <UploadDocument isOpen={showUploadDocDialog} onClose={() => setShowUploadDocDialog(false)} projectId={project?.id} />
      </CardFooter>
    </Card>
  );
};

export default LayerList;
