#!/usr/bin/env python3
"""Generate the secrets and keys self-hosted Langfuse needs, into .env.

Append-only and idempotent: keys already present in .env are left alone,
so running it twice changes nothing. Backs .env up first (mode 600) and
never prints a secret value.

    python scripts/setup_langfuse.py [--env-file .env] [--admin-email you@example.com]
    docker compose --profile langfuse up -d
    # then recreate the app so it picks up the keys:
    docker compose up -d app && docker restart mundi-nginx
"""
from __future__ import annotations

import argparse
import os
import re
import secrets
import shutil
import sys
import time
import uuid
from pathlib import Path


def _generated(admin_email: str) -> dict[str, str]:
    return {
        "LANGFUSE_NEXTAUTH_SECRET": secrets.token_urlsafe(32),
        "LANGFUSE_SALT": secrets.token_urlsafe(32),
        # Langfuse requires exactly 64 hex characters.
        "LANGFUSE_ENCRYPTION_KEY": secrets.token_hex(32),
        "LANGFUSE_DB_PASSWORD": secrets.token_urlsafe(24),
        "LANGFUSE_CLICKHOUSE_PASSWORD": secrets.token_urlsafe(24),
        "LANGFUSE_REDIS_PASSWORD": secrets.token_urlsafe(24),
        "LANGFUSE_MINIO_PASSWORD": secrets.token_urlsafe(24),
        "LANGFUSE_PUBLIC_KEY": f"pk-lf-{uuid.uuid4()}",
        "LANGFUSE_SECRET_KEY": f"sk-lf-{uuid.uuid4()}",
        "LANGFUSE_ADMIN_EMAIL": admin_email,
        "LANGFUSE_ADMIN_PASSWORD": secrets.token_urlsafe(18),
    }


def _existing_keys(text: str) -> set[str]:
    return set(re.findall(r"(?m)^\s*(?:export\s+)?([A-Z0-9_]+)\s*=", text))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--env-file", default=".env")
    parser.add_argument("--admin-email", default="admin@ingabe.local")
    parser.add_argument("--backup-dir", help="where to back .env up (default: next to it)")
    args = parser.parse_args()

    env_path = Path(args.env_file)
    text = env_path.read_text() if env_path.exists() else ""
    present = _existing_keys(text)
    missing = {k: v for k, v in _generated(args.admin_email).items() if k not in present}
    if not missing:
        print(f"Langfuse keys already present in {env_path}; nothing to do.")
        return 0

    if env_path.exists():
        backup_dir = Path(args.backup_dir) if args.backup_dir else env_path.parent
        backup = backup_dir / f"{env_path.name}.bak-langfuse-{time.strftime('%Y%m%d-%H%M%S')}"
        shutil.copy2(env_path, backup)
        os.chmod(backup, 0o600)
        print(f"Backed up {env_path} to {backup} (mode 600).")

    block = ["", "# ---- Langfuse (Sage flight recorder), generated by scripts/setup_langfuse.py ----"]
    block += [f"{key}={value}" for key, value in missing.items()]
    with env_path.open("a") as fh:
        if text and not text.endswith("\n"):
            fh.write("\n")
        fh.write("\n".join(block) + "\n")
    os.chmod(env_path, 0o600)

    print(f"Added to {env_path}: {', '.join(missing)}")
    if "LANGFUSE_ADMIN_PASSWORD" in missing:
        print(f"Langfuse login: {args.admin_email}; password is LANGFUSE_ADMIN_PASSWORD in {env_path}.")
    print("Next: docker compose --profile langfuse up -d, then recreate the app container.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
